### ISSUE TITLE
name issue with crate.io

### ISSUE THREAD

**Issue by bgkillas** [konkitoman/kalc#1]
just wondering if you are still using this for i would like to claim the name on crates.io. started my project around the end of april but never really thought of using crates.io until now https://github.com/bgkillas/kalc

**Comment by konkitoman** [comment]
I'am fine with that!
So i should add you on crates.io as an owner on that project, and i will re-upload mine as kalc-kman?

**Comment by bgkillas** [comment]
sure that will probably work fine

**Comment by konkitoman** [comment]
I added you, you probably receive an email from crates.io!

**Comment by konkitoman** [comment]
I re-published mine as kalc-kman!

**Comment by bgkillas** [comment]
thanks everything seems fine now :)
